version: '3'
services:
    db:
    syncstorage-rs:
        # TODO: either syncstorage-rs should retry the db connection
        # itself a few times or should include a wait-for-it.sh script
        # inside its docker that would do this for us. Same (probably
        # the latter solution) for server-syncstorage below
        entrypoint: >
          /bin/sh -c "
            sleep 15;
            /app/bin/syncstorage;
          "
    e2e:
        depends_on:
          - syncstorage-rs
        entrypoint: >
          /bin/ash -c "
            sleep 18;
            python3 /app/tools/integration_tests/run.py 'http://syncstorage-rs:8000#secret0'
          "
